# Generated by Django 4.2.30 on 2026-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cuestionario_alter_zona_id_ruta_pregunta_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={},
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='orden',
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
